
#+title: Polybar Configuration
#+PROPERTY: header-args :tangle /home/jon/.config/polybar/config :mkdirp yes

* Tips for use
If you're looking at this file in Emacs, you can put your cursor on a link and press =C-c C-o= or run =M-x org-open-at-point= to open the link in your web browser. [[https://github.com/polybar/polybar][polybar docs]]

* Colors

#+begin_src conf

[colors]
background = #222
background-alt = #444
foreground = #dfdfdf
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

#+end_src

* Bar

[[https://github.com/polybar/polybar/wiki/Configuration][Bar Configuration]]

#+begin_src conf

[bar/my-bar]
width = 100%
height = 30
fixed-center = false
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 0
padding-right = 2

border-top = 2
border-color = #12e884

module-margin-left = 1
module-margin-right = 2

font-0 = fixed:pixelsize=11;1
font-1 = unifont:fontformat=truetype:size=10:antialias=false;0
font-2 = siji:pixelsize=10;1

modules-left = i3
modules-right = pulseaudio memory cpu eth date 

tray-position = right
tray-padding = 2

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

#+end_src

* Modules
** Alsa

[[https://github.com/polybar/polybar/wiki/Module:-alsa][Alsa Documentation]]

This module shows volume and mute state for ALSA mixers. Most of the module functionality should work as long as you are using an alsa backend.

IMPORTANT: Do not use this module if you are using pulseaudio

#+begin_src conf

[module/alsa]
type = internal/alsa

format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

#+end_src

** Backlight-acpi

[[https://github.com/polybar/polybar/wiki/Module:-backlight][Backlight Documentation]]

This module shows information about the current monitor backlight setting.

#+begin_src conf

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

#+end_src

** Battery

[[https://github.com/polybar/polybar/wiki/Module:-battery][Battery Documentation]]

This module shows information about the battery.

#+begin_src conf

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-foreground = ${colors.foreground-alt}
animation-discharging-framerate = 750

#+end_src

** bspwm

[[https://github.com/polybar/polybar/wiki/Module:-bspwm][BPSWM Documentation]]

This module uses the bspwm ipc client to display information about available monitors, desktops and layout states.

#+begin_src conf

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

; Separator in between workspaces
; label-separator = |

#+end_src

** CPU

[[https://github.com/polybar/polybar/wiki/Module:-cpu][CPU Documentation]]

This module shows information about the current CPU load.

#+begin_src conf

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU: "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage:2%%

#+end_src

** Date

[[https://github.com/polybar/polybar/wiki/Module:-date][Date Documentation]]

This module shows information about the current date.

NOTE: This module supports most—but not all—of the formatting sequences that can be found in man date. For example, to display the time in 12-hour format, you can use either %I:%M or %l:%M for a 0-padded hour or a space-padded hour respectively.

Formatting sequences such as %-I (12-hour time without padding) will not work. Use a custom script with the date command as a workaround.

#+begin_src conf

[module/date]
type = internal/date
interval = 1

date =
date-alt = " %A the %d | %B/%Y"

time = %A %I:%M:%S %p
time-alt = %H:%M:%S

label = %date% %time%

;hidden = true

#+end_src

** Filesystem

[[https://github.com/polybar/polybar/wiki/Module:-filesystem][Filesystem Documentation]]

This module shows information about mounted filesystems.

NOTE: The module is currently limited to mountpoints.

#+begin_src conf

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

#+end_src

** i3

[[https://github.com/polybar/polybar/wiki/Module:-i3][i3 Documentation]]

This module uses the i3 ipc to display information about workspaces and active mode.

#+begin_src conf

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
;pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

; Separator in between workspaces
; label-separator = |

#+end_src

** MPD

[[https://github.com/polybar/polybar/wiki/Module:-mpd][mpd Documentation]]

This module shows information related to [[https://www.musicpd.org][MPD]].

#+begin_src conf

[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

#+end_src

** Memory

[[https://github.com/polybar/polybar/wiki/Module:-memory][Memory Documentation]]

This module shows information about the current memory usage.

#+begin_src conf

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM: "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used%%

#+end_src

** Network

[[https://github.com/polybar/polybar/wiki/Module:-network][Network Documentation]]

This module shows information about the specified network interface.

NOTE: If you use both a wired and a wireless network, you need two module definitions if you want both to be displayed. For example:

#+begin_src conf :tangle no

[module/wired-network]
type = internal/network
interface = eth1

[module/wireless-network]
type = internal/network
interface = wlan1

#+end_src

*** Eth

#+begin_src conf

[module/eth]
type = internal/network
interface = enp0s3
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = "Eth: "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

#+end_src

*** Wlan

#+begin_src conf

[module/wlan]
type = internal/network
interface = net1
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

#+end_src

** PowerMenu

This is a custom menu to give power options if you click the power button in the bottom right corner. It is based on the "Menu" module.

[[https://github.com/polybar/polybar/wiki/Module:-menu][Menu Documentation]]

This module lets you create text menus. It is possible to control the menu using [[https://github.com/polybar/polybar/wiki/Inter-process-messaging][Inter-process messaging]].

Note: With version 3.5.0, the way to open and close the menu levels has changed. In particular, if you use =menu-open-*= or =menu-close= in your menu module, you should update the module to use the new action names. A guide for this can be found [[https://polybar.readthedocs.io/en/stable/user/actions.html#deprecated-action-names][here]].

Basic settings

The menu module uses [[https://polybar.readthedocs.io/en/stable/user/actions.html][actions]] for opening and closing menu levels. For example to open level N, the action is =open.N=, to close the menu, the action is called =close=. Please read the link above to learn how to construct the full action string.

#+begin_src conf

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

#+end_src

** Pulseaudio

[[https://github.com/polybar/polybar/wiki/Module:-pulseaudio][PulseAudio Documentation]]

This module shows volume and mute state for Pulseaudio. It uses the specified sink in the config if available, and uses the default sink if it is not available or provided.

#+begin_src conf

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> <bar-volume>
label-volume = VOL %percentage%%
label-volume-foreground = ${root.foreground}

label-muted = 🔇 muted
label-muted-foreground = #666

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

#+end_src

** Temperature

[[https://github.com/polybar/polybar/wiki/Module:-temperature][Temperature Documentation]]

This module shows the information about the current temperature.

#+begin_src conf

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

#+end_src

** xBacklight

[[https://github.com/polybar/polybar/wiki/Module:-xbacklight][xBacklight Documentation]]

This module shows information about the defined output's backlight level.

#+begin_src conf

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

#+end_src

** xKeyboard

[[https://github.com/polybar/polybar/wiki/Module:-xkeyboard][xKeyboard Documentation]]

This module shows the current layout and active indicators.

If there are more than one layout configured for the keyboard there will be a click handler attached to the module that will cycle the ones found.

#+begin_src conf

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

#+end_src

** xWindow

[[https://github.com/polybar/polybar/wiki/Module:-xwindow][xwindow documentation]]

This modulle shows the title of the currently focused window.

NOTE: This requires a WM that supports the EWHM atom _NET_ACTIVE_WINDOW

#+begin_src conf

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

#+end_src

* Settings

#+begin_src conf

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

#+end_src

* Global/wm

#+begin_src conf

[global/wm]
margin-top = 5
margin-bottom = 5

; vim:ft=dosini

#+end_src

* Tangle this file on save
;; Local Variables:
;; eval: (add-hook 'after-save-hook (lambda() (if(y-or-n-p "Tangle?")(org-babel-tangle))) nil t)
;; End:



